### ISSUE TITLE
[TRACKER] Documentation Overhaul

### ISSUE THREAD

**Issue by Pyxus** [Pyxus/fray#74]
This issue tracks progress of the ongoing documentation overhaul. The goal of this overhaul is to improve the readability, correctness, and usefulness of  the current documentation including both doc-comments and markdown docs.

The present "getting started page" attempts to explain each module in it's entirety. However, these pages are difficult to digest since they tell users how and why, but don't make it clear what problem the module tools will solve for them. As such the getting started page is going to be replaced by a series of guides which explain how to use the tools in Fray to solve common problems. If you would like to suggest a guide to be added please reply with a description of the guide, or create an issue and reply with a link to the issue. I'm focusing on guides for aspects of each module, but guides that showcase how to use multiple modules together are desired. Additionally, if you have any objections to this idea let me know your thoughts.

If you would like to help me with the documentation overhaul simply create PR and leave a reply linking to the PR and stating what it covers. This page will be updated as progress is made.

# Doc-Comments

_Doc-comment PRs will be divided by folders within a module._

-  [ ] Collision: /* PR:
- [ ] Collision: 2d/* PR:
- [ ] Collision: 3d/* PR:
- [ ] Input: autoloads/* PR:
- [ ] Input: /* PR:
- [ ] Input: device/binds/* PR:
- [ ] Input: device/composites/* PR:
- [ ] Input: events/* PR:
- [ ] Input: sequence/* PR:
- [ ] StateMgmt: /* PR:
- [ ] StateMgmt: state/* PR:
- [ ] StateMgmt: transition/* PR:
- [ ] fray.gd PR:

# Guides

- [ ] README.md: Provides an overview of what fray is, what problems it solves / what features it has, and how to install. PR:
- [ ] Using Hitboxes: Covers the purpose of hitboxes, how to create them, and how to extend them using attributes. PR:
- [ ] Managing Multiple Hitboxes: Covers the the issue of managing multiple hitboxes, the purpose/use of hit states, and the purpose/use of hit state managers. PR:
- [ ] Detecting Inputs: Covers purpose/registration of binds, purpose/registration of composite inputs, checking inputs. PR:
- [ ] Detecting Input Sequences: Covers what a sequence is, use of sequence trees, purpose of negative edge, use of negative edge, use of sequence matcher. PR:

Note: The present guide proposals are based on the existing getting started page. Since state management was refactored I need to re-evaluate what needs to be covered before I add state-related guides to the tracker.

# Issues to Address
#59
#44
#23
